### PR TITLE
fix(types): make `extra` optional on `graphqlHTTP` and `graphqlWS`

### LINKED ISSUE #38: Should the 'extra' argument be optional on graphqlHTTP?
Hello there 👋

I started trying out Benzene for a personal project, and I'm developing mostly in TypeScript. While following the [Getting Started](https://benzene.vercel.app/getting-started) guide I came across the following error:

image

I'm wondering if this `extra` argument should be optional instead? 🤔

### PR DESCRIPTION
**Pull request by rfgamaral**
Closes #38

### CODE REVIEW

**Comment by hoangvvo** [comment]
Could you also make the same change in graphqlWS? Thanks!

**Comment by rfgamaral** [comment]
> 
> 
> Could you also make the same change in graphqlWS? Thanks!

Sure, I'll take care of it soon.

**Comment by rfgamaral** [comment]
@hoangvvo Pushed a similar change for `graphqlWS`, not sure if I did this one right, and I wasn't able to figure out how to implement a test for this one, sorry.

File: packages/ws/src/types.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ export interface ConnectionContext<TExtra> {
   // Whether the server has received connection init request from the client
   connectionInitReceived: boolean;
   // The "extra" variable
-  extra: TExtra;
+  extra?: TExtra;
```
Comment (hoangvvo) [inline packages/ws/src/types.ts:52]: This is always defined (only it might just be `undefined` (https://github.com/hoangvvo/benzene/blob/main/packages/ws/src/handler.ts#L167). You can leave it as it.
```suggestion
  extra: TExtra;
```

**Comment by hoangvvo** [comment]
> @hoangvvo Pushed a similar change for `graphqlWS`, not sure if I did this one right, and I wasn't able to figure out how to implement a test for this one, sorry.

Hey, thanks a lot for the change. No worry, I have added a test case. I left one tiny change request and then it should be good to go!

**Comment by rfgamaral** [comment]
Should be good to go :)

Do you think we can have a new release after merging this? :)

**Comment by hoangvvo** [comment]
> Should be good to go :)
> 
> Do you think we can have a new release after merging this? :)

Yeah definitely!

**Review by hoangvvo — APPROVED** [review]
LGTM. Thanks a lot!
